### ISSUE TITLE
timeoutError

### ISSUE THREAD

**Issue by NUCL3ARN30N** [XternA/honeygain-reward#1]
Hi,
I get the following error - It worked previously but recently this happens:

```
2024-11-03T14:03:40.209027491Z ------------ Honeygain Pot Auto Claim ------------

2024-11-03T14:03:40.209495223Z Starting login process...

2024-11-03T14:04:14.721022168Z /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:50

2024-11-03T14:04:14.721277260Z             this.#timeoutError = new Errors_js_1.TimeoutError(`Waiting failed: ${options.timeout}ms exceeded`);

2024-11-03T14:04:14.721288431Z                                  ^

2024-11-03T14:04:14.721294672Z 

2024-11-03T14:04:14.721300894Z TimeoutError: Waiting for selector `.sc-gKAaef.eFCJQX` failed: Waiting failed: 30000ms exceeded

2024-11-03T14:04:14.721306896Z     at new WaitTask (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/WaitTask.js:50:34)

2024-11-03T14:04:14.721311705Z     at IsolatedWorld.waitForFunction (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Realm.js:25:26)

2024-11-03T14:04:14.721316274Z     at CSSQueryHandler.waitFor (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/QueryHandler.js:172:95)

2024-11-03T14:04:14.721320712Z     at runNextTicks (node:internal/process/task_queues:65:5)

2024-11-03T14:04:14.721325401Z     at listOnTimeout (node:internal/timers:555:9)

2024-11-03T14:04:14.721329789Z     at process.processTimers (node:internal/timers:529:7)

2024-11-03T14:04:14.721334488Z     at async CdpFrame.waitForSelector (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Frame.js:523:21)

2024-11-03T14:04:14.721339297Z     at async CdpPage.waitForSelector (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/api/Page.js:1367:20)

2024-11-03T14:04:14.721343575Z     at async /app/run.js:1:3041

2024-11-03T14:04:14.721348134Z 

2024-11-03T14:04:14.721352201Z Node.js v22.8.0

2024-11-03T14:04:14.731640949Z Honeygain exited with code 1. ❌

2024-11-03T14:04:14.731696084Z Re-attempting again in 2 hours ⏱️

2024-11-03T14:04:14.732501313Z Time logged: 14:04:14
```

**Comment by XternA** [comment]
You'll need to pull the latest image as you're running an older version. The website changed its CSS element hence why it's broken.

Consider using [Income Generator Tool](https://github.com/XternA/income-generator) which will auto-update the app in the future, or you will need `Watchtower` if you want to configure it manually for auto updating the container image.
